### ISSUE TITLE
Deliver xml file at the publication to DG

### ISSUE THREAD

**Issue by eliselavy** [C2DH/journal-of-digital-history-backend#130]
In order to facilitate the availability of the DOI at the publication, we go to deliver an XML's file at the same time at the pdf.
The DOI with crossref will be available after 24 hours.

**2 block parts:**

- journal-meta
- article-meta

journal-meta: fix part
ISSN: 2747-5271 + jdh 

article-meta:

**ppbub: to discuss to define for JDH**
The publication date, for the printable version, in our case equal to epub.
```
<pub-date pub-type="ppub">
        <day>01</day>
	<month>09</month>
	<year>2021</year>
</pub-date>
```

**epub: to discuss to define for JDH**
The electronic date , when the article is published online
```
<pub-date pub-type="epub">
	<day>12</day>
	<month>04</month>
	<year>2022</year>
</pub-date>
```
```
<pub-date pub-type="cover-date">
	<day>01</day>
	<month>09</month>
	<year>2021</year>
</pub-date>
```
**cover-date: to discuss to define for JDH**

<img width="794" alt="Screenshot 2022-06-21 at 15 08 15" src="https://user-images.githubusercontent.com/35602279/174806849-4a492d86-4e44-418a-921f-22fbc59e1fd3.png">

**Comment by inactinique** [comment]
Why epub? Just the publication of the first article on the JDH website, I would say?

**Comment by eliselavy** [comment]
@inactinique 
cover-date / ppub / epub are requested information by  de gruyter, theses xml fields are requested in order to generate a proper indexation of their side.

epub in the date when the article has been published on our side
my question is about cover-date , it seems it will be in our case the epub of the first article on the issue?

**Comment by inactinique** [comment]
I would say that cover-date = the date of the publication of the first article on our website, whatever the date of publication of the first epub is.

**Comment by eliselavy** [comment]
@inactinique
I forgot to mention, for each article published, a xml 's file  will be generated.
An article belongs to an issue, for me the cover-date is not static date == to the publication of the first article on our website but 
If the article belongs to issue 3, the cover-date will be set to the date of the first article published of the issue 3, no?

**Comment by inactinique** [comment]
yes, exactly.

**Comment by eliselavy** [comment]
Copyright statement:
© <YEAR> <AUTHOR or ORGANIZATION / FUNDER>. Published by De Gruyter in cooperation with the University of Luxembourg Centre for Contemporary and Digital History. This is an Open Access article distributed under the terms of the Creative Commons Attribution License CC-BY-NC-ND https://creativecommons.org/licenses/by-nc-nd/4.0/

**Comment by eliselavy** [comment]
@lwieneke this copyright statement is the one included in the article itself : <img width="926" alt="Screenshot 2022-06-28 at 09 53 41" src="https://user-images.githubusercontent.com/35602279/176124778-ee29e20e-7cb8-424d-b906-07419cbb4c94.png">

**Comment by lwieneke** [comment]
I think that the XML version of the statement is a more "machine-readable" approach. So the easiest solution would be to replace
`<copyright-holder>Louis Autin, published by Walter de Gruyter GmbH, Berlin/Boston</copyright-holder>`
with
`<copyright-holder>Louis Autin, published by Walter de Gruyter GmbH, Berlin/Boston in cooperation with the University of Luxembourg Centre for Contemporary and Digital History</copyright-holder>`

However, we should discuss with Bendix if this is actually a good place for this addendum for the <copyright-holder>. Technically speaking it's information about the publisher but it's not related to the copyright holder itself.

**Comment by eliselavy** [comment]
About the seq 
<img width="901" alt="Screenshot 2022-07-29 at 16 38 13" src="https://user-images.githubusercontent.com/35602279/181786566-3528c12a-9ce3-475e-822e-0492e1f02383.png">

**Comment by eliselavy** [comment]
<elocation-id seq="TO DEFINE">TO DEFINE</elocation-id> need to be provided

**Comment by eliselavy** [comment]
In development

**Comment by eliselavy** [comment]
In production

**Comment by eliselavy** [comment]
Variable: {elocation-id}=[{article-system-creation-date-year}](http://www.wiki.degruyter.de/production/files/dg_variables_and_id.xhtml#article-system-creation-date-year) [{article-counter-ID}](http://www.wiki.degruyter.de/production/files/dg_variables_and_id.xhtml#article-counter-id)

last 4 digits of the DOI

**Comment by eliselavy** [comment]
@bendix3 The changes have been deployed in production but still some question:

- I still don't know what to put for the  seq  <elocation-id seq="TO DEFINE">20211004</elocation-id>

Now epub / cover-date / issue are in place

```
<pub-date pub-type="epub">
<day>19</day>
<month>01</month>
<year>2022</year>
</pub-date>
<pub-date pub-type="cover-date">
<day>18</day>
<month>10</month>
<year>2021</year>
</pub-date>
<pub-date pub-type="issue">
<day>18</day>
<month>10</month>
<year>2021</year>
</pub-date>
<volume>1</volume>
<issue>>1</issue>
<elocation-id seq="TO DEFINE">20211004</elocation-id>
```

**Comment by bendix3** [comment]
Hi @eliselavy, sincere apologies for the delay!

The seq attribute is only required for articles that are part of an issue. I believe the idea is to publish thematic open issues where articles are added when ready. In this case, you can give the first article the seq attribute value 1, but if you add an editorial later that is then supposed to precede the article that was published first, the value would have to be adjusted for proper presentation on degruyter.com – in case that matters.

**Comment by eliselavy** [comment]
@bendix3 a new version has been deployed in order to integrate the seq
editorial is always on seq=1
