### ISSUE TITLE
Identify all the manual steps perform during the technical review  and automatize

### ISSUE THREAD

**Issue by eliselavy** [C2DH/journal-of-digital-history-backend#172]
Identify all the manual steps perform during the technical review  in order to perform automatically

**Comment by eliselavy** [comment]
- sh script to generate requirements.txt https://github.com/C2DH/journal-of-digital-history-backend/issues/181
- rename figure label
- check if media ressources used

**Comment by eliselavy** [comment]
- check all urls mentionned and check availability

script need to be integrated here: https://github.com/C2DH/journal-of-digital-history-ipynb-preflight-action/actions/runs/4342893071/jobs/7584262436

**Comment by eliselavy** [comment]
- made script to check the output size of the cell (with https://pythontic.com/modules/pickle/dumps)
- part of the process to control size of the output

**Comment by eliselavy** [comment]
For the external library, add a check on the output 
```
"outputs": [
    {
     "data": {
      "text/html": [
       "        require.undef(\"plotly\");\n",
       "        **define**('plotly', function(require, exports, module) {\n",
```

**Comment by eliselavy** [comment]
For the citation as cite2c and citation manager don't take into account the group , add a check by calling zotero api

**Comment by biumiamy** [comment]
For the [script result](https://github.com/C2DH/journal-of-digital-history-ipynb-preflight-action/blob/master/report.md), added a first demo gif to the guideline

**Comment by eliselavy** [comment]
For the checkoutput.py

Need to look at all type of outputs:
- "image/png"
- "text/html"
     if contains <table check if tagged / metadata correct
-  following one also : ![Screenshot 2023-08-17 at 16 15 49](https://github.com/C2DH/journal-of-digital-history-backend/assets/35602279/90570a96-3bdc-4976-a20a-1c8f32c8728f)

- https://docs.jupyter.org/en/latest/reference/mimetype.html

**Comment by eliselavy** [comment]
Need to improve the checkurl: https://github.com/C2DH/journal-of-digital-history-ipynb-preflight-action/blob/master/checks/checkurls.py
as many urls here are valid and considered as false https://github.com/jdh-observer/m5GhKrrErgfE/blob/main/report.md

**Comment by eliselavy** [comment]
Problem to run the action: https://github.com/jdh-observer/FYjDViXVXggz/actions/runs/6262624601/job/17005229904#step:12:147

![Screenshot 2023-09-21 at 15 55 22](https://github.com/C2DH/journal-of-digital-history-backend/assets/35602279/500ebb35-5156-4b16-b70e-fc284507b4c8)

**Comment by eliselavy** [comment]
Script more restrictive in github action
`Error: Invalid format '- https://licensebuttons.net/l/by/4.0/88x31.png)](https://creativecommons.org/licenses/by/4.0/ returned a 404 status code.'`

https://github.com/jdh-observer/m5GhKrrErgfE/actions/runs/6263047507/job/17006567430

**Comment by eliselavy** [comment]
Deliver in the https://github.com/C2DH/template_repo_JDH and in the https://github.com/C2DH/template_repo_JDH_R

**Comment by eliselavy** [comment]
Tested action : https://github.com/marketplace/actions/markdownlint-cli2-action
But permissive with html tag
https://github.com/jdh-observer/48RGuzM4qfVA/actions/runs/6654446381
