### ISSUE TITLE
Solution for copy-editing, look for markdown export

### ISSUE THREAD

**Issue by eliselavy** [C2DH/journal-of-digital-history-backend#175]
Idea to use the ReviewNB. for copy editing https://www.reviewnb.com/ ( now at each repo of jdh-observer will be added)
But still someone need to add the comments
Look at if copy-editor can work on the markdown and could be merge automatically.
Check if preservation of the cell
- With Nbconvert
- With https://jupytext.readthedocs.io/en/latest/using-cli.html

**Comment by eliselavy** [comment]
<img width="711" alt="Screenshot 2023-01-31 at 14 31 06" src="https://user-images.githubusercontent.com/35602279/215774108-92411dd3-f2e9-451b-8588-351804444017.png">

**Comment by eliselavy** [comment]
syncronisation md / ipynb  
"jupytext": {
   "formats": "ipynb,md"
  },

**Comment by eliselavy** [comment]
request an export in md file:

`jupytext --to markdown notebook.ipynb `          # convert notebook.ipynb to a .md file

**Comment by eliselavy** [comment]
TO DO:
- find a good editor to review md file
- automatisation generation markdown

**Comment by biumiamy** [comment]
It's very comfortable to edit in the md file, much better than the Jupyter Notebook tbh. But not sure it would be good for Andy.. but looking at what a copyeditor did then via ReviewNB afterwards could be nice
