### ISSUE TITLE
Check feasibility of moving to thebe ecosystem

### ISSUE THREAD

**Issue by biumiamy** [C2DH/journal-of-digital-history-backend#188]
- check feasibility
- issue about previous non-interactive articles 

benefits of switching
- interactive data
- potential for book project
- ...

**Comment by biumiamy** [comment]
Make notebook code interactive #280
https://github.com/C2DH/journal-of-digital-history/issues/280

**Comment by eliselavy** [comment]
![Image](https://github.com/C2DH/journal-of-digital-history-backend/assets/35602279/3fc3d446-6b34-4350-bbba-68104effde4a)

**Comment by danieleguido** [comment]
React thebe example for the frontend on https://github.com/executablebooks/thebe/blob/main/apps/demo-react/
For github issue see https://github.com/C2DH/journal-of-digital-history/issues/280

**Comment by eliselavy** [comment]
Appointment 09/06 with @stevejpurves

**Comment by eliselavy** [comment]
- Test pull request  https://github.com/C2DH/journal-of-digital-history/tree/feature/thebe see comments: https://github.com/C2DH/journal-of-digital-history/issues/552#issuecomment-1706891421
- Review documentation: https://mystmd.org/thebe/architecture
- Look at journal https://journal.physiomeproject.org/ integration by Curvenotes
- Test demo: https://github.com/executablebooks/thebe/tree/main/apps/demo-react/public
Problem by choosing myBinder:

![Image](https://github.com/C2DH/journal-of-digital-history-backend/assets/35602279/07ba0fe5-5b24-4878-afdf-fe794b2a0fcc)

**Comment by eliselavy** [comment]
In order to work locally start the JupyterLab with following command: 
`jupyter lab --NotebookApp.token='test-secret' --NotebookApp.allow_origin='*'`

To use the Binder, thebe-main/apps/demo-react/src/App.tsx  
```
binderOptions: {
        repo: 'executablebooks/thebe-binder-base',
      },
```

**Comment by eliselavy** [comment]
About design:
- will be tricky to be able to customize the [Jupyter Widget](https://ipywidgets.readthedocs.io/en/stable/)
- buttons / action bar will be customizable
Example coming from https://www.elementalmicroscopy.com/
![Screenshot 2023-09-06 at 11 34 30](https://github.com/C2DH/journal-of-digital-history-backend/assets/35602279/50c9ac9d-83af-4bf5-b0df-41ea91426dff)

**Comment by eliselavy** [comment]
Proposal sent - wait for feedback of secretary

**Comment by eliselavy** [comment]
order form sent at Cuvernote

**Comment by eliselavy** [comment]
Order accepted
Kick-off meeting planned for 9 November
Mission will start 13 November
