### ISSUE TITLE
Check the integration of the Issue 2 in DG website

### ISSUE THREAD

**Issue by eliselavy** [C2DH/journal-of-digital-history-backend#189]
Here on the website https://www.degruyter.com/journal/key/jdh/html#latestIssue

I successfully uploaded the first Open Issue article (jdh-2021-1009) to our submission checker today. Attached, you can find both the successful package and the submission checker report that marks the errors for the first attempt, on which I based the manual adjustments of the article XML I found on your website. I also write them down here for convenience / transparency, with corresponding error letters in the beginning:
 
Error A: The <volume> tag must contain the content-type attribute with the value open-issue: <volume content-type="open-issue">2</volume>
Errors B and C: The elocation ID contains only of the numbers of the DOI, i.e. the journal code is omitted: <elocation-id seq="1">20211009</elocation-id>
Error (was already corrected here): The PDF and the XML had incorrect city and country information for the second author. I corrected both manually. It is important that the PDF is correct as well in this regard, as some A&I services such as Web of Science also analyze PDF data and compare it with the XML / use it to enrich their databases.
Errors D and E: Just like other tags, <contrib-id> must not be empty. If no ID was provided by the author, please omit this tag. (or we can make ORCID iDs mandatory in ScholarOne…)

**Comment by bendix3** [comment]
@eliselavy the online team takes their time, just received a Jira helpdesk ticket status update today that this is now in progress. Unfortunately manual work is required and it takes some time.

**Comment by eliselavy** [comment]
@bendix3 crossref have been integrated - url tested - ok
