### ISSUE TITLE
Dataverse url to be added at the article level for next release

### ISSUE THREAD

**Issue by eliselavy** [C2DH/journal-of-digital-history-backend#201]
- Dataverse url to be added at the article level for next release
-  To test also https://github.com/marketplace/actions/dataverse-uploader-action
- Dataset need to be PUBLISHED - not stay in DRAFT

**Comment by eliselavy** [comment]
Problem to add dataset https://data.journalofdigitalhistory.org/   
- with files
- without files
=> no feedback of the interface 
<img width="1425" alt="Screenshot 2023-08-29 at 13 05 01" src="https://github.com/C2DH/journal-of-digital-history-backend/assets/35602279/6e82e0f8-7a0a-472c-b5f7-4a254613af57">

**Comment by c2dhfma** [comment]
2023-08-28, nothing to worry about in the log.

2023-08-29, this exception was raised:
[2023-08-29T11:53:40.364+0200] [Payara 5.2022.4] [SEVERE] [] [javax.enterprise.resource.webcontainer.jsf.context] [tid: _ThreadID=70 _ThreadName=http-thread-pool::http-listener-1(4)] [timeMillis: 1693302820364] [levelValue: 1000] [[
  javax.faces.application.ViewExpiredException: viewId:/dataset.xhtml - View /dataset.xhtml could not be restored.

Dataverse lost the connection to the DB on the 9th, this has probably put the server in an inconsistent state.

Updated Dataverse to 5.14, all seems ok.
Tested the creation of :
- a dataverse https://data.journalofdigitalhistory.org/dataverse.xhtml?alias=testfma
- a dataset https://data.journalofdigitalhistory.org/dataset.xhtml?persistentId=doi:10.5072/FK2/RW80RT&version=DRAFT
- a file https://data.journalofdigitalhistory.org/file.xhtml?fileId=306&version=DRAFT

**Comment by eliselavy** [comment]
@c2dhfma can you extend the duration of the session as it was before 30 minutes.

**Comment by eliselavy** [comment]
Session extended + addition dataset solved @c2dhfma 
wait now the answer of DG about the DOI for the dataset: 
we want to give access to the datasets that are associated to the articles in the journal and for this purpose it would be good to have a dedicated DOI for them. So how do you do this usually? Do you amend the DOI of the article or do you use completely different DOIs? The hosting of the dataset would take place on our dataverse instance for the journal.
