### ISSUE TITLE
abstract primary key using shortuuid lib

### ISSUE THREAD

**Issue by danieleguido** [C2DH/journal-of-digital-history-backend#6]
add a field  id in the Abstract model:

create a method for id generation :
```python
import shortuuid
def create_short_url():
    return shortuuid.uuid()[:12]  # es => "IRVaY2b3VI89"
```

Dans le model:
```
pid = models.CharField(max_length=255, primary_key=True, default=create_short_url)
```

**Comment by eliselavy** [comment]
Problem to have a primary key with many to many table.
django.db.utils.DataError: invalid input syntax for type integer: "Y2oef6YXasX5"
LINE 1: ...) WHERE "jdhapi_abstract_authors"."abstract_id" = 'Y2oef6YXa...
Play with db_index , db_column , need more time to figure out how the join table  jdhapi_abstract_authors use the abstract_id
