### ISSUE TITLE
Linked abstract submission to CFP 

### ISSUE THREAD

**Issue by eliselavy** [C2DH/journal-of-digital-history-backend#88]
Linked abstract submission to CFP

**Comment by eliselavy** [comment]
linked to https://github.com/C2DH/journal-of-digital-history/issues/335

**Comment by eliselavy** [comment]
@inactinique available in production
In the dashboard abstract submission , addition column call of paper
<img width="1197" alt="Screenshot 2022-09-26 at 18 15 06" src="https://user-images.githubusercontent.com/35602279/192328802-d144509f-27ed-428c-817a-38492cedfabf.png">

> Please look at the abstracts already submitted before this implementation
I attach some abstract to the call of paper _History Seeing Through the Web_ but possible mistake could have been made.
TO DO IT: connect to admin and on the abstract model, select the appropriate call of paper as below
<img width="645" alt="Screenshot 2022-09-26 at 18 15 44" src="https://user-images.githubusercontent.com/35602279/192329882-567f92f6-3d99-47de-a990-f3d41edef72e.png">

IN FUTURE abstract submission , they will be linked directly to the call of paper


History Seeing Through the Web
--


<br class="Apple-interchange-newline">

History Seeing Through the Web
--


<br class="Apple-interchange-newline">

History Seeing Through the Web
--


<br class="Apple-interchange-newline">

**Comment by inactinique** [comment]
I don't see the line 'Callpaper' for this one: https://journalofdigitalhistory.org/admin/jdhapi/abstract/53/change/

**Comment by eliselavy** [comment]
fixed with https://github.com/C2DH/journal-of-digital-history-backend/commit/f599e844297aad973f56d249c42639805685015e
