### ISSUE TITLE
Docker image : prepare Half-day Workshop and Tutorial for Digital Humanities Conference 2022: 25 or 26 july

### ISSUE THREAD

**Issue by eliselavy** [C2DH/journal-of-digital-history-backend#98]
We are happy to inform you that your submission to the Digital Humanities 2022 conference, "Writing a multilayered article for the Journal of Digital History", has been accepted as a Half-day Workshop and Tutorial.

This year, we received over 500 proposals, and the quality and diversity of the proposals were outstanding. Reviewers and the Program Committee diligently reviewed and considered all submissions.

DH2022 will take place 25-29 July 2022 and be entirely online. Workshops, tutorials, and SIGs (special interest groups) will meet on Monday 25 July and Tuesday 26 July. 
Half-day workshop and tutorial slots can be reserved for up to 3 hours, not including breaks.
If you do not need technical support from the local organizer, you can extend the time slot (by an hour) or hold the workshop in a different time zone than Japan time.
In the days and weeks to come, you will receive more specific information about scheduling and future operations.

**Comment by eliselavy** [comment]
Use this functionnality: https://help.webex.com/en-us/article/nyg3cqeb/Show-your-video-over-shared-content-in-Webex-Meetings-and-Webex-Webinars

**Comment by eliselavy** [comment]
https://github.com/jupyter/docker-stacks

Jupyter Docker Stacks are a set of ready-to-run [Docker images](https://hub.docker.com/u/jupyter) containing Jupyter applications and interactive computing tools. You can use a stack image to do any of the following (and more):
•	Start a personal Jupyter Server with JupyterLab frontend (default)
•	Run JupyterLab for a team using JupyterHub
•	Start a personal Jupyter Notebook server in a local Docker container
•	Write your own project Dockerfile
https://github.com/antonpirker/jupyter-vagrant-box


https://www.vagrantup.com/

This is a simple Vagrant virtual machine. It contains a setup for running Jupyter notebook with Python 3. The setup includes the [Anaconda Python distribution](https://www.anaconda.com/distribution/) which means a lot of data science packages like [NumPy](http://www.numpy.org/), [pandas](https://pandas.pydata.org/), [matplotlib](https://matplotlib.org/), [Bokeh](https://bokeh.pydata.org/en/latest/) and many more are readily included in the setup.

**Comment by eliselavy** [comment]
https://github.com/C2DH/journal-of-digital-history-jupyter-stack

Docker image published: https://hub.docker.com/r/c2dhunilu/journal-of-digital-history-jupyter

**Comment by inactinique** [comment]
J'arrive à la faire marcher, mais je n'ai aucune idée de la manière dont on peut accéder au notebook lancé. Ça ne marche pas sur localhost:8888
